
/*
 * sprites.S
 *
 * Created: 6/29/2017 8:57:29 PM
 *  Author: Andrew
 */ 

.global speed_000
.global speed_005
.global speed_010
.global speed_015
.global speed_020
.global speed_025
.global speed_030
.global speed_035
.global speed_040
.global speed_045
.global speed_050
.global speed_055
.global speed_060
.global speed_065
.global speed_070
.global speed_075
.global speed_080
.global speed_085
.global speed_090
.global speed_095
.global speed_100


speed_000:
.byte 0x00
speed_005:
.byte 0x00
speed_010:
.byte 0x00
speed_015:
.byte 0x00
speed_020:
.byte 0x00
speed_025:
.byte 0x00
speed_030:
.byte 0x00
speed_035:
.byte 0x00
speed_040:
.byte 0x00
speed_045:
.byte 0x00
speed_050:
.byte 0x00
speed_055:
.byte 0x00
speed_060:
.byte 0x00
speed_065:
.byte 0x00
speed_070:
.byte 0x00
speed_075:
.byte 0x00
speed_080:
.byte 0x00
speed_085:
.byte 0x00
speed_090:
.byte 0x00
speed_095:
.byte 0x00
speed_100:
.byte 0x00